server:
  port: 1205
  servlet:
    context-path: "/banking"

spring:
  datasource:
    url: "jdbc:mysql://localhost/bank"
    username: "root"
    password: "system"
  sql:
    init:
      mode: ALWAYS
  jpa:
    hibernate:
      ddl-auto: update

upload:
  file:
    name: "profile-pictures/"

